/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReelComment = IDL.Record({
  'id' : IDL.Nat,
  'userName' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'reelId' : IDL.Nat,
});
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'deliveryLocation' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const ProductSummary = IDL.Record({
  'id' : IDL.Nat,
  'mrp' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'inStock' : IDL.Bool,
  'discountAmount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'colours' : IDL.Vec(IDL.Text),
});
export const Reel = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'productId' : IDL.Opt(IDL.Nat),
  'videoUrl' : IDL.Text,
});
export const Scheme = IDL.Record({
  'id' : IDL.Nat,
  'couponCode' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
});
export const Voucher = IDL.Record({
  'id' : IDL.Nat,
  'value' : IDL.Nat,
  'code' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'orderId' : IDL.Text,
});
export const PaymentSettings = IDL.Record({
  'qrImage' : IDL.Vec(IDL.Nat8),
  'qrImageType' : IDL.Text,
  'upiId' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'mrp' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'inStock' : IDL.Bool,
  'imageType' : IDL.Text,
  'discountAmount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'image' : IDL.Vec(IDL.Nat8),
  'colours' : IDL.Vec(IDL.Text),
});
export const ProductImage = IDL.Record({
  'imageData' : IDL.Vec(IDL.Nat8),
  'imageType' : IDL.Text,
});
export const RatingSummary = IDL.Record({
  'count' : IDL.Nat,
  'average' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addProductImage' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat8), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addReelComment' : IDL.Func([IDL.Nat, IDL.Text], [ReelComment], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [Category], []),
  'createOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Text, IDL.Text],
      [Order],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Record({
          'mrp' : IDL.Nat,
          'categoryId' : IDL.Nat,
          'inStock' : IDL.Bool,
          'imageType' : IDL.Text,
          'discountAmount' : IDL.Nat,
          'name' : IDL.Text,
          'description' : IDL.Text,
          'sizes' : IDL.Vec(IDL.Text),
          'image' : IDL.Vec(IDL.Nat8),
          'colours' : IDL.Vec(IDL.Text),
        }),
      ],
      [ProductSummary],
      [],
    ),
  'createReel' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [Reel],
      [],
    ),
  'createScheme' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Scheme],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteOrder' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteReel' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteScheme' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'generateDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], []),
  'getAllVouchers' : IDL.Func([IDL.Text], [IDL.Vec(Voucher)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getInstagramHandle' : IDL.Func([], [IDL.Text], ['query']),
  'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrderDeliveryCode' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getPaymentSettings' : IDL.Func([], [IDL.Opt(PaymentSettings)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductImages' : IDL.Func([IDL.Nat], [IDL.Vec(ProductImage)], ['query']),
  'getProductRating' : IDL.Func([IDL.Nat], [RatingSummary], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(ProductSummary)], ['query']),
  'getReelComments' : IDL.Func([IDL.Nat], [IDL.Vec(ReelComment)], ['query']),
  'getReelLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
  'getSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
  'getTheme' : IDL.Func([], [IDL.Text], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProductRating' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserVouchers' : IDL.Func([IDL.Principal], [IDL.Vec(Voucher)], ['query']),
  'getUserWishlist' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Nat)], ['query']),
  'isReelLiked' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], ['query']),
  'likeReel' : IDL.Func([IDL.Nat], [], []),
  'rateProduct' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  'removeProductImage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setInstagramHandle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setPaymentSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text],
      [],
      [],
    ),
  'setTheme' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'unlikeReel' : IDL.Func([IDL.Nat], [], []),
  'updateCategory' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Category], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Record({
          'mrp' : IDL.Nat,
          'categoryId' : IDL.Nat,
          'inStock' : IDL.Bool,
          'imageType' : IDL.Text,
          'discountAmount' : IDL.Nat,
          'name' : IDL.Text,
          'description' : IDL.Text,
          'sizes' : IDL.Vec(IDL.Text),
          'image' : IDL.Vec(IDL.Nat8),
          'colours' : IDL.Vec(IDL.Text),
        }),
      ],
      [ProductSummary],
      [],
    ),
  'verifyDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReelComment = IDL.Record({
    'id' : IDL.Nat,
    'userName' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'reelId' : IDL.Nat,
  });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'deliveryLocation' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const ProductSummary = IDL.Record({
    'id' : IDL.Nat,
    'mrp' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'inStock' : IDL.Bool,
    'discountAmount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'colours' : IDL.Vec(IDL.Text),
  });
  const Reel = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'productId' : IDL.Opt(IDL.Nat),
    'videoUrl' : IDL.Text,
  });
  const Scheme = IDL.Record({
    'id' : IDL.Nat,
    'couponCode' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
  });
  const Voucher = IDL.Record({
    'id' : IDL.Nat,
    'value' : IDL.Nat,
    'code' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'orderId' : IDL.Text,
  });
  const PaymentSettings = IDL.Record({
    'qrImage' : IDL.Vec(IDL.Nat8),
    'qrImageType' : IDL.Text,
    'upiId' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'mrp' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'inStock' : IDL.Bool,
    'imageType' : IDL.Text,
    'discountAmount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'image' : IDL.Vec(IDL.Nat8),
    'colours' : IDL.Vec(IDL.Text),
  });
  const ProductImage = IDL.Record({
    'imageData' : IDL.Vec(IDL.Nat8),
    'imageType' : IDL.Text,
  });
  const RatingSummary = IDL.Record({
    'count' : IDL.Nat,
    'average' : IDL.Float64,
  });
  
  return IDL.Service({
    'addProductImage' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat8), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addReelComment' : IDL.Func([IDL.Nat, IDL.Text], [ReelComment], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [Category], []),
    'createOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Text, IDL.Text],
        [Order],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Record({
            'mrp' : IDL.Nat,
            'categoryId' : IDL.Nat,
            'inStock' : IDL.Bool,
            'imageType' : IDL.Text,
            'discountAmount' : IDL.Nat,
            'name' : IDL.Text,
            'description' : IDL.Text,
            'sizes' : IDL.Vec(IDL.Text),
            'image' : IDL.Vec(IDL.Nat8),
            'colours' : IDL.Vec(IDL.Text),
          }),
        ],
        [ProductSummary],
        [],
      ),
    'createReel' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [Reel],
        [],
      ),
    'createScheme' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Scheme],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteOrder' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteReel' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteScheme' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'generateDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], []),
    'getAllVouchers' : IDL.Func([IDL.Text], [IDL.Vec(Voucher)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getInstagramHandle' : IDL.Func([], [IDL.Text], ['query']),
    'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrderDeliveryCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getPaymentSettings' : IDL.Func([], [IDL.Opt(PaymentSettings)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductImages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductImage)],
        ['query'],
      ),
    'getProductRating' : IDL.Func([IDL.Nat], [RatingSummary], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(ProductSummary)], ['query']),
    'getReelComments' : IDL.Func([IDL.Nat], [IDL.Vec(ReelComment)], ['query']),
    'getReelLikeCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
    'getSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
    'getTheme' : IDL.Func([], [IDL.Text], ['query']),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProductRating' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserVouchers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Voucher)],
        ['query'],
      ),
    'getUserWishlist' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'isReelLiked' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], ['query']),
    'likeReel' : IDL.Func([IDL.Nat], [], []),
    'rateProduct' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
    'removeProductImage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setInstagramHandle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setPaymentSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text],
        [],
        [],
      ),
    'setTheme' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'unlikeReel' : IDL.Func([IDL.Nat], [], []),
    'updateCategory' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Category], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Record({
            'mrp' : IDL.Nat,
            'categoryId' : IDL.Nat,
            'inStock' : IDL.Bool,
            'imageType' : IDL.Text,
            'discountAmount' : IDL.Nat,
            'name' : IDL.Text,
            'description' : IDL.Text,
            'sizes' : IDL.Vec(IDL.Text),
            'image' : IDL.Vec(IDL.Nat8),
            'colours' : IDL.Vec(IDL.Text),
          }),
        ],
        [ProductSummary],
        [],
      ),
    'verifyDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };