/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : bigint, 'name' : string }
export interface Order {
  'id' : string,
  'status' : string,
  'paymentMethod' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'deliveryLocation' : string,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export interface PaymentSettings {
  'qrImage' : Uint8Array,
  'qrImageType' : string,
  'upiId' : string,
}
export interface Product {
  'id' : bigint,
  'mrp' : bigint,
  'categoryId' : bigint,
  'inStock' : boolean,
  'imageType' : string,
  'discountAmount' : bigint,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'image' : Uint8Array,
  'colours' : Array<string>,
}
export interface ProductImage { 'imageData' : Uint8Array, 'imageType' : string }
export interface ProductSummary {
  'id' : bigint,
  'mrp' : bigint,
  'categoryId' : bigint,
  'inStock' : boolean,
  'discountAmount' : bigint,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'colours' : Array<string>,
}
export interface RatingSummary { 'count' : bigint, 'average' : number }
export interface Reel {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'productId' : [] | [bigint],
  'videoUrl' : string,
}
export interface ReelComment {
  'id' : bigint,
  'userName' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'text' : string,
  'reelId' : bigint,
}
export interface Scheme {
  'id' : bigint,
  'couponCode' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'whatsapp' : string,
}
export interface Voucher {
  'id' : bigint,
  'value' : bigint,
  'code' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'orderId' : string,
}
export interface _SERVICE {
  'addProductImage' : ActorMethod<[string, bigint, Uint8Array, string], bigint>,
  'addReelComment' : ActorMethod<[bigint, string], ReelComment>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'createCategory' : ActorMethod<[string, string], Category>,
  'createOrder' : ActorMethod<[Array<OrderItem>, string, string], Order>,
  'createProduct' : ActorMethod<
    [
      string,
      {
        'mrp' : bigint,
        'categoryId' : bigint,
        'inStock' : boolean,
        'imageType' : string,
        'discountAmount' : bigint,
        'name' : string,
        'description' : string,
        'sizes' : Array<string>,
        'image' : Uint8Array,
        'colours' : Array<string>,
      },
    ],
    ProductSummary
  >,
  'createReel' : ActorMethod<[string, string, string, [] | [bigint]], Reel>,
  'createScheme' : ActorMethod<[string, string, string, string], Scheme>,
  'deleteCategory' : ActorMethod<[string, bigint], undefined>,
  'deleteOrder' : ActorMethod<[string, string], undefined>,
  'deleteProduct' : ActorMethod<[string, bigint], undefined>,
  'deleteReel' : ActorMethod<[string, bigint], undefined>,
  'deleteScheme' : ActorMethod<[string, bigint], undefined>,
  'generateDeliveryCode' : ActorMethod<[string, string], string>,
  'getAllOrders' : ActorMethod<[string], Array<Order>>,
  'getAllUsers' : ActorMethod<[string], Array<UserProfile>>,
  'getAllVouchers' : ActorMethod<[string], Array<Voucher>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getDeliveryCode' : ActorMethod<[string, string], [] | [string]>,
  'getInstagramHandle' : ActorMethod<[], string>,
  'getOrderById' : ActorMethod<[string], [] | [Order]>,
  'getOrderDeliveryCode' : ActorMethod<[string], [] | [string]>,
  'getPaymentSettings' : ActorMethod<[], [] | [PaymentSettings]>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductImages' : ActorMethod<[bigint], Array<ProductImage>>,
  'getProductRating' : ActorMethod<[bigint], RatingSummary>,
  'getProducts' : ActorMethod<[], Array<ProductSummary>>,
  'getReelComments' : ActorMethod<[bigint], Array<ReelComment>>,
  'getReelLikeCount' : ActorMethod<[bigint], bigint>,
  'getReels' : ActorMethod<[], Array<Reel>>,
  'getSchemes' : ActorMethod<[], Array<Scheme>>,
  'getTheme' : ActorMethod<[], string>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProductRating' : ActorMethod<[bigint], [] | [bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserVouchers' : ActorMethod<[Principal], Array<Voucher>>,
  'getUserWishlist' : ActorMethod<[Principal], Array<bigint>>,
  'isReelLiked' : ActorMethod<[bigint, Principal], boolean>,
  'likeReel' : ActorMethod<[bigint], undefined>,
  'rateProduct' : ActorMethod<[bigint, bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'removeProductImage' : ActorMethod<[string, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'setInstagramHandle' : ActorMethod<[string, string], undefined>,
  'setPaymentSettings' : ActorMethod<
    [string, string, Uint8Array, string],
    undefined
  >,
  'setTheme' : ActorMethod<[string, string], undefined>,
  'unlikeReel' : ActorMethod<[bigint], undefined>,
  'updateCategory' : ActorMethod<[string, bigint, string], Category>,
  'updateOrderStatus' : ActorMethod<[string, string, string], undefined>,
  'updateProduct' : ActorMethod<
    [
      string,
      bigint,
      {
        'mrp' : bigint,
        'categoryId' : bigint,
        'inStock' : boolean,
        'imageType' : string,
        'discountAmount' : bigint,
        'name' : string,
        'description' : string,
        'sizes' : Array<string>,
        'image' : Uint8Array,
        'colours' : Array<string>,
      },
    ],
    ProductSummary
  >,
  'verifyDeliveryCode' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];