/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : bigint, 'name' : string }
export interface Order {
  'id' : string,
  'status' : string,
  'paymentMethod' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'deliveryLocation' : string,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export interface PaymentSettings {
  'qrImage' : Uint8Array,
  'qrImageType' : string,
  'upiId' : string,
}
export interface Product {
  'id' : bigint,
  'mrp' : bigint,
  'categoryId' : bigint,
  'inStock' : boolean,
  'imageType' : string,
  'discountAmount' : bigint,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'image' : Uint8Array,
  'colours' : Array<string>,
}
export interface ProductSummary {
  'id' : bigint,
  'mrp' : bigint,
  'categoryId' : bigint,
  'inStock' : boolean,
  'discountAmount' : bigint,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'colours' : Array<string>,
}
export interface Scheme {
  'id' : bigint,
  'couponCode' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'whatsapp' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Voucher {
  'id' : bigint,
  'value' : bigint,
  'code' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'orderId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface Reel {
  'id' : bigint,
  'title' : string,
  'videoUrl' : string,
  'productId' : [] | [bigint],
  'createdAt' : bigint,
}
export interface RatingSummary {
  'average' : number,
  'count' : bigint,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string], Category>,
  'createOrder' : ActorMethod<[Array<OrderItem>, string, string], Order>,
  'createProduct' : ActorMethod<
    [
      string,
      {
        'mrp' : bigint,
        'categoryId' : bigint,
        'inStock' : boolean,
        'imageType' : string,
        'discountAmount' : bigint,
        'name' : string,
        'description' : string,
        'sizes' : Array<string>,
        'image' : Uint8Array,
        'colours' : Array<string>,
      },
    ],
    ProductSummary
  >,
  'createScheme' : ActorMethod<[string, string, string, string], Scheme>,
  'deleteCategory' : ActorMethod<[string, bigint], undefined>,
  'deleteProduct' : ActorMethod<[string, bigint], undefined>,
  'deleteScheme' : ActorMethod<[string, bigint], undefined>,
  'getAllOrders' : ActorMethod<[string], Array<Order>>,
  'getAllUsers' : ActorMethod<[string], Array<UserProfile>>,
  'getAllVouchers' : ActorMethod<[string], Array<Voucher>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getOrderById' : ActorMethod<[string], [] | [Order]>,
  'getPaymentSettings' : ActorMethod<[], [] | [PaymentSettings]>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<ProductSummary>>,
  'getSchemes' : ActorMethod<[], Array<Scheme>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserVouchers' : ActorMethod<[Principal], Array<Voucher>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'setPaymentSettings' : ActorMethod<[string, string, Uint8Array, string], undefined>,
  'updateCategory' : ActorMethod<[string, bigint, string], Category>,
  'updateOrderStatus' : ActorMethod<[string, string, string], undefined>,
  'createReel' : ActorMethod<[string, string, string, [] | [bigint]], Reel>,
  'deleteReel' : ActorMethod<[string, bigint], undefined>,
  'generateDeliveryCode' : ActorMethod<[string, string], string>,
  'getDeliveryCode' : ActorMethod<[string, string], [] | [string]>,
  'getProductRating' : ActorMethod<[bigint], RatingSummary>,
  'getReels' : ActorMethod<[], Array<Reel>>,
  'getTheme' : ActorMethod<[], string>,
  'getUserWishlist' : ActorMethod<[Principal], Array<bigint>>,
  'rateProduct' : ActorMethod<[bigint, bigint], undefined>,
  'setTheme' : ActorMethod<[string, string], undefined>,
  'verifyDeliveryCode' : ActorMethod<[string, string], boolean>,
  'updateProduct' : ActorMethod<
    [
      string,
      bigint,
      {
        'mrp' : bigint,
        'categoryId' : bigint,
        'inStock' : boolean,
        'imageType' : string,
        'discountAmount' : bigint,
        'name' : string,
        'description' : string,
        'sizes' : Array<string>,
        'image' : Uint8Array,
        'colours' : Array<string>,
      },
    ],
    ProductSummary
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
