/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'deliveryLocation' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'mrp' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'inStock' : IDL.Bool,
  'imageType' : IDL.Text,
  'discountAmount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'image' : IDL.Vec(IDL.Nat8),
  'colours' : IDL.Vec(IDL.Text),
});
// Lightweight summary returned by getProducts(), createProduct(), updateProduct()
export const ProductSummary = IDL.Record({
  'id' : IDL.Nat,
  'mrp' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'inStock' : IDL.Bool,
  'discountAmount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'colours' : IDL.Vec(IDL.Text),
});
export const Scheme = IDL.Record({
  'id' : IDL.Nat,
  'couponCode' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
});
export const Voucher = IDL.Record({
  'id' : IDL.Nat,
  'value' : IDL.Nat,
  'code' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'orderId' : IDL.Text,
});
export const PaymentSettings = IDL.Record({
  'qrImage' : IDL.Vec(IDL.Nat8),
  'qrImageType' : IDL.Text,
  'upiId' : IDL.Text,
});


export const Reel = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'videoUrl' : IDL.Text,
  'productId' : IDL.Opt(IDL.Nat),
  'createdAt' : IDL.Int,
});

export const RatingSummary = IDL.Record({
  'average' : IDL.Float64,
  'count' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [Category], []),
  'createOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Text, IDL.Text],
      [Order],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Record({
          'mrp' : IDL.Nat,
          'categoryId' : IDL.Nat,
          'inStock' : IDL.Bool,
          'imageType' : IDL.Text,
          'discountAmount' : IDL.Nat,
          'name' : IDL.Text,
          'description' : IDL.Text,
          'sizes' : IDL.Vec(IDL.Text),
          'image' : IDL.Vec(IDL.Nat8),
          'colours' : IDL.Vec(IDL.Text),
        }),
      ],
      [ProductSummary],
      [],
    ),
  'createScheme' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Scheme], []),
  'deleteCategory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteScheme' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], []),
  'getAllVouchers' : IDL.Func([IDL.Text], [IDL.Vec(Voucher)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getPaymentSettings' : IDL.Func([], [IDL.Opt(PaymentSettings)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(ProductSummary)], ['query']),
  'getSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserVouchers' : IDL.Func([IDL.Principal], [IDL.Vec(Voucher)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setPaymentSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text],
      [],
      [],
    ),
  'updateCategory' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Category], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Record({
          'mrp' : IDL.Nat,
          'categoryId' : IDL.Nat,
          'inStock' : IDL.Bool,
          'imageType' : IDL.Text,
          'discountAmount' : IDL.Nat,
          'name' : IDL.Text,
          'description' : IDL.Text,
          'sizes' : IDL.Vec(IDL.Text),
          'image' : IDL.Vec(IDL.Nat8),
          'colours' : IDL.Vec(IDL.Text),
        }),
      ],
      [ProductSummary],
      [],
    ),
  'createReel' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)], [Reel], []),
  'deleteReel' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'generateDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getProductRating' : IDL.Func([IDL.Nat], [RatingSummary], ['query']),
  'getReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
  'getTheme' : IDL.Func([], [IDL.Text], ['query']),
  'getUserWishlist' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Nat)], ['query']),
  'rateProduct' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setTheme' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'verifyDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'deliveryLocation' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'mrp' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'inStock' : IDL.Bool,
    'imageType' : IDL.Text,
    'discountAmount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'image' : IDL.Vec(IDL.Nat8),
    'colours' : IDL.Vec(IDL.Text),
  });
  const ProductSummary = IDL.Record({
    'id' : IDL.Nat,
    'mrp' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'inStock' : IDL.Bool,
    'discountAmount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'colours' : IDL.Vec(IDL.Text),
  });
  const Scheme = IDL.Record({
    'id' : IDL.Nat,
    'couponCode' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
  });
  const Voucher = IDL.Record({
    'id' : IDL.Nat,
    'value' : IDL.Nat,
    'code' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'orderId' : IDL.Text,
  });
  const PaymentSettings = IDL.Record({
    'qrImage' : IDL.Vec(IDL.Nat8),
    'qrImageType' : IDL.Text,
    'upiId' : IDL.Text,
  });
  const Reel = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'videoUrl' : IDL.Text,
    'productId' : IDL.Opt(IDL.Nat),
    'createdAt' : IDL.Int,
  });
  const RatingSummary = IDL.Record({
    'average' : IDL.Float64,
    'count' : IDL.Nat,
  });

  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [Category], []),
    'createOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Text, IDL.Text],
        [Order],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Record({
            'mrp' : IDL.Nat,
            'categoryId' : IDL.Nat,
            'inStock' : IDL.Bool,
            'imageType' : IDL.Text,
            'discountAmount' : IDL.Nat,
            'name' : IDL.Text,
            'description' : IDL.Text,
            'sizes' : IDL.Vec(IDL.Text),
            'image' : IDL.Vec(IDL.Nat8),
            'colours' : IDL.Vec(IDL.Text),
          }),
        ],
        [ProductSummary],
        [],
      ),
    'createScheme' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Scheme], []),
    'deleteCategory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteScheme' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], []),
    'getAllVouchers' : IDL.Func([IDL.Text], [IDL.Vec(Voucher)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getPaymentSettings' : IDL.Func([], [IDL.Opt(PaymentSettings)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(ProductSummary)], ['query']),
    'getSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserVouchers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Voucher)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setPaymentSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text],
        [],
        [],
      ),
    'updateCategory' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Category], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Record({
            'mrp' : IDL.Nat,
            'categoryId' : IDL.Nat,
            'inStock' : IDL.Bool,
            'imageType' : IDL.Text,
            'discountAmount' : IDL.Nat,
            'name' : IDL.Text,
            'description' : IDL.Text,
            'sizes' : IDL.Vec(IDL.Text),
            'image' : IDL.Vec(IDL.Nat8),
            'colours' : IDL.Vec(IDL.Text),
          }),
        ],
        [ProductSummary],
        [],
      ),
    'createReel' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)], [Reel], []),
    'deleteReel' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'generateDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getProductRating' : IDL.Func([IDL.Nat], [RatingSummary], ['query']),
    'getReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
    'getTheme' : IDL.Func([], [IDL.Text], ['query']),
    'getUserWishlist' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Nat)], ['query']),
    'rateProduct' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setTheme' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'verifyDeliveryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };
